services:
  - type: web
    name: lilac-backend-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    healthCheckPath: /api/services
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://postgres.ruhozpbikwpppcdqnhbo:Ajsspc@9910@aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres
